version: '3.8'
services:
  rest-wallets:
    build: ./
    image: rest-wallets:latest
    command: ./wait-for-postgres.sh db ./app
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - config.env
  db:
    restart: always
    image: postgres:latest
    volumes:
    - pgdata:/var/lib/postgresql/data
    env_file:
      - config.env
    ports:
      - 5436:5432
      
volumes:
  pgdata: